# docker compose 配置redis slave
# 1主2从,两个slave复制master的数据
# docker-compose -f master-slave.yml up -d
version: '3'
services:
  master:
    image: redis:latest
    container_name: master
    networks:
      slave_default2:
        ipv4_address: 172.16.10.10
  slave1:
    image: redis:latest
    container_name: slave1
    depends_on:
      - master
    networks:
      slave_default2:
        ipv4_address: 172.16.10.12
  slave2:
    image: redis:latest
    container_name: slave2
    depends_on:
      - master
      - slave1
    networks:
      slave_default2:
        ipv4_address: 172.16.10.11
    command:
      - /bin/sh
      - -c
      - |
        echo "sleep 3 \
        && redis-cli -h 172.16.10.10 -p 6379 slaveof no one \
        && redis-cli -h 172.16.10.12 -p 6379 slaveof 172.16.10.10 6379\
        && redis-cli slaveof 172.16.10.10 6379" >> run.sh
        /bin/bash run.sh
        redis-server
networks:
  slave_default2:
    driver: bridge
    name: slave_default2
    ipam:
      config:
        - subnet: "172.16.10.0/16"
          gateway: "172.16.10.1"