version: '3.1'
services:
  zoo1:
    container_name: zoo_1
    image: zookeeper
    restart: always
    hostname: zoo1
    networks:
      kafka_default2:
        ipv4_address: 172.16.14.21
    ports:
      - 2181:2181

  broker1:
    container_name: broker1
    image: wurstmeister/kafka
    depends_on:
      - zoo1
    networks:
      kafka_default2:
        ipv4_address: 172.16.14.11
    ports:
      - "9092:9092"
      - "7203:7203"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: broker1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HOST_NAME: broker1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://172.16.14.11:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.14.11:9092

  broker2:
    container_name: broker2
    image: wurstmeister/kafka
    networks:
      kafka_default2:
        ipv4_address: 172.16.14.12
    ports:
      - "9093:9092"
    depends_on:
      - zoo1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: broker2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HOST_NAME: broker2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://172.16.14.12:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.14.12:9092

  broker3:
    container_name: broker3
    image: wurstmeister/kafka
    networks:
      kafka_default2:
        ipv4_address: 172.16.14.13
    ports:
      - "9094:9092"
    depends_on:
      - zoo1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: broker3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HOST_NAME: broker3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://172.16.14.13:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.14.13:9092

# kafka-topics.sh --zookeeper zoo1:2181 --list

networks:
  kafka_default2:
    driver: bridge
    name: kafka_default2
    ipam:
      config:
        - subnet: "172.16.14.0/16"
          gateway: "172.16.14.1"
